FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir kafka-python requests

COPY telemetryIngester.py historicraceproducer.py ./

CMD ["python", "historicraceproducer.py"]
